theme: jekyll-theme-minimal
title: ğŸ™‹ğŸ¼â€â™‚ï¸ Ğ˜Ğ»ÑŒÑ ĞĞ±Ñ€Ğ¾ÑĞºĞ¸Ğ½
description: email: [ilya.abroskinn@gmail.com](mailto:ilya.abroskinn@gmail.com), telegram: [iiiiilllllyyyyyaaaa](t.me/iiiiilllllyyyyyaaaa)
github:
  is_project_page: false
